file_format: "1"
id: skeletyl
name: skeletyl
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - skeletyl_left
  - skeletyl_right
